# Generated by Django 5.1.6 on 2025-05-06 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminstaff',
            name='username',
        ),
    ]
