# Generated by Django 5.1.6 on 2025-05-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_remove_adminstaff_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('other_names', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('level', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=100)),
                ('matric_number', models.CharField(max_length=50, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
            ],
        ),
    ]
