# Generated by Django 5.1.6 on 2025-05-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0003_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('SOCIOLOGY', 'Sociology'), ('ECONOMICS', 'Economics'), ('POLITICAL_SCIENCE', 'Political Science'), ('COMPUTER_SCIENCE', 'Computer Science'), ('MASS_COMMUNICATION', 'Mass Communication'), ('ACCOUNTING_FINANCE', 'Accounting & Finance'), ('PUBLIC_ADMINISTRATION', 'Public Administration'), ('BUSINESS_ADMINISTRATION', 'Business Administration'), ('HUMAN_RESOURCE', 'Human Resource Management'), ('INTERNATIONAL_RELATIONS', 'International Relations & Diplomacy'), ('ENVIRONMENTAL_HEALTH', 'Environmental Health Management'), ('COMMUNITY_HEALTH', 'Community Health Management'), ('NURSING', 'Nursing')], max_length=50),
        ),
    ]
