# Generated by Django 5.1.6 on 2025-05-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0004_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Sociology', 'Sociology'), ('Economics', 'Economics'), ('Political Science', 'Political Science'), ('Computer Science', 'Computer Science'), ('Mass Communication', 'Mass Communication'), ('Accounting & Finance', 'Accounting & Finance'), ('Public Administration', 'Public Administration'), ('Business Administration', 'Business Administration'), ('Human Resource Management', 'Human Resource Management'), ('International Relation & Diplomacy', 'International Relations & Diplomacy'), ('Environmental Health Management', 'Environmental Health Management'), ('Community Health Management', 'Community Health Management'), ('Nursing', 'Nursing')], max_length=50),
        ),
    ]
